### PR TITLE
fence_compute: Add --insecure and --region-name command line arguments

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by aspiers** [comment]
+1

**Comment by beekhof** [comment]
They don't appear to be used anywhere.  Is there a second patch?

**Comment by vuntz** [comment]
> They don't appear to be used anywhere. Is there a second patch?

They're used when creating the client object (in the nova_client.Client() call)

**Comment by aspiers** [comment]
@vuntz wrote:
> They're used when creating the client object (in the nova_client.Client() call)

A URL pointing to this would probably help the review process.

In any case it would be great if this be merged now, as it's blocking https://review.openstack.org/#/c/264975/.  Thanks :)

**Comment by vuntz** [comment]
>> They're used when creating the client object (in the nova_client.Client() call)
> 
> A URL pointing to this would probably help the review process.

Hrm, it's in this pull request... https://github.com/ClusterLabs/fence-agents/pull/37/files#diff-a9401fa3fb78f30aae7a079ece083575R352-353

**Comment by aspiers** [comment]
Ah right, thanks - I didn't notice because github hid the context around the diff.

**Pull request merged**
