### PR TITLE
fence_lpar: Support comanaged LPARs

### PR DESCRIPTION
**Pull request by hramrach**
When the managed system has NovaLink installed it is still possible to
manage the system with HMC with correct chcomgmgt setting but profiles
are not supported.

@watologo1

### CODE REVIEW

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
retest this please

**Comment by watologo1** [comment]
I cannot find any hint to what caused the build failure...?
@oalbrigt 
Any advise how to get further here would be appreciated. Thanks.

**Comment by wenningerk** [comment]
> I cannot find any hint to what caused the build failure...? @oalbrigt Any advise how to get further here would be appreciated. Thanks.

Looks like coverity is stumbling over stuff in the c-code and python-code.
Although there are findings with fence_lpar.py the plethora of findings makes me
think that we are seeing some issue with the base-line - maybe triggered by renaming master to main ...

**Comment by hramrach** [comment]
What are the problems reported in python code?

I seer only problems in C code in the report.

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Pull request merged**
