### PR TITLE
fence_aliyun: import EcsRamRoleCredential

### PR DESCRIPTION
**Pull request by dongchen126**
Add  "EcsRamRoleCredential" class from aliyun SDK

### CODE REVIEW

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
It seems like this includes all the updates from https://github.com/ClusterLabs/fence-agents/pull/279.

Can you rebase, so we dont get duplicates of these commits in the tree?

**Comment by dongchen126** [comment]
finished rebase

**Comment by oalbrigt** [comment]
It seems like the rebase failed (it added a Merge commit, instead of getting rid of all the former commits that has already been merged).

**Comment by dongchen126** [comment]
Done, please kindly help to check,thanks

**Comment by oalbrigt** [comment]
It still has all the code from that other PR.

Try running the following 2 commands to rebase it:
```
git remote add upstream git@github.com:ClusterLabs/fence-agents.git
git rebase upstream/master
```

**Comment by oalbrigt** [comment]
I pulled your commit into a branch, rebased and merged in #286. Thanks.

**Pull request closed without merging**
