### PR TITLE
fence_redfish: Add diag action

### PR DESCRIPTION
**Pull request by nrwahl2**
Sends NMI to fenced node.

Ref:
  - http://redfish.dmtf.org/schemas/DSP2046_2020.3.html#redfish.dmtf.org/schemas/v1/ComputerSystem.json|details|ResetType

Resolves: RHBZ#1920947

Signed-off-by: Reid Wahl <nrwahl@protonmail.com>

**Note**: This is a WIP because I don't have the necessary hardware to test this.

### CODE REVIEW

**Comment by oalbrigt** [comment]
LGTM.

**Comment by nrwahl2** [comment]
After someone with the required hardware can test this in the BZ, I'll flip out of Draft status.

**Comment by oalbrigt** [comment]
We can merge it now, so we can get some early feedback from upstream if anyone tries it.

**Comment by nrwahl2** [comment]
Go for it :)

**Comment by oalbrigt** [comment]
Thanks.

**Pull request merged**
