### PR TITLE
Mid: fence_scsi,fence_mpath: Add suppress-errors option.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi Oyvind,
Hi All, 

This fix fixes the issue presented in the next issue.
 - https://github.com/ClusterLabs/fence-agents/issues/482

Add --suppress-errors to /etc/sysconfig/stonith to suppress the logs output when used with the watchdog service.

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
You need to run `make xml-upload` and attach the updated metadata for CI to pass.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

> You need to run `make xml-upload` and attach the updated metadata for CI to pass.

Thanks for your comment.
I'll give it a try.
If that doesn't work, let me ask you about the procedure.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

I ran make xml-upload and pushed.
How is it?

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
LGTM, so now we just have to wait and see if CI agrees :)

**Comment by oalbrigt** [comment]
Thanks.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Okay!

Many thanks,
Hideo Yamauchi.

**Pull request merged**
