### PR TITLE
fence_vbox: Add a fencing agent for VirtualBox

### PR DESCRIPTION
**Pull request by krig**
Adds a fencing agent for virtual machines managed by VirtualBox.

Based on fence_virsh, tested with VirtualBox version 5.0.4 on
openSUSE 13.2.

### CODE REVIEW

**Comment by digimer** [comment]
Glad to see this! The more environments we support, the better. :D

**Comment by marxsk** [comment]
Hi krig,

thanks for fence agent. I have just two comments that may be worth fixing:
* line73: time.sleep(...) -> this should be done in fencing library. if it does not work it is my bug, just let me know. 
* You have used 'missing_as_opt' option which really makes sense (and I should port it to fence_virsh too) but this option has to be turned on by user (--missing-as-off). This is not a case for your code, simple 'if "--missing-as-off" in options' should solve this issue. 

I will wait for next upstream release, so it can be included.

**Comment by krig** [comment]
@marxsk Good catch, thank you! Pushed fixes to submit request.

**Comment by marxsk** [comment]
Great thanks, last very minor issue :) please merge it to one commit. thanks,

**Comment by krig** [comment]
@marxsk done :)

**Pull request merged**
