### PR TITLE
Update fence_rcd_serial to correct vendor URL

### PR DESCRIPTION
**Pull request by sammcj**
* Correct vendor URL to https://github.com/sammcj/fence_rcd_serial
* Update RHEL/CentOS version currently agent currently tested with
* Update Copyright date

For more information on this provider, see: https://smcleod.net/tech/2016/07/04/update-rcd-stonith-design.html

### CODE REVIEW

**Comment by oalbrigt** [comment]
You need to run "make xml-upload" to update the metadata and add it to the PR to avoid CI failing.

**Comment by sammcj** [comment]
Whoops & thanks, I’ll do that tomorrow :)

--
Sam McLeod

**Comment by sammcj** [comment]
I was a bit stumped by this and am now left with blank test xml files due to a python library error in the make target.

After seeing that [the makefile](https://github.com/ClusterLabs/fence-agents/blob/master/Makefile.am) doesn't mention a target of `make xml-upload` anywhere I figured out that I needed to:

1. Run a `./autogen.sh` 
1. Run a `./configure`
1. Install the package requirements that were missing in the `./configure`

However this doesn't seem to generate or test for all the required files / packages / libs are installed as running `make xml-upload` generates a wall of python errors (despite exiting 0) and all the test XML is blank / empty:

```shell
root@dev-samm-01:~/git/fence-agents-sammcj  # make xml-upload
...
for x in fence_rcd_serial `PYTHONPATH=/root/git/fence-agents-sammcj/lib:/root/git/fence-agents-sammcj/lib /bin/python rcd_serial/fence_rcd_serial -o metadata | grep symlink | sed -e "s/.*\(fence.*\)\" .*/\1/g"`; do \
	PYTHONPATH=/root/git/fence-agents-sammcj/lib:/root/git/fence-agents-sammcj/lib /bin/python rcd_serial/$x -o metadata | gawk 'BEGIN {store=-1} /name=\".*_path\"/ {store=2} {if (store!=0) {print}; store--}' > /root/git/fence-agents-sammcj/tests/data/metadata/$x.xml; \
done
Traceback (most recent call last):
  File "rcd_serial/fence_rcd_serial", line 25, in <module>
    from fencing import *
ImportError: No module named fencing
...
make[1]: Leaving directory `/root/git/fence-agents-sammcj/agents'
Making xml-upload in doc
make[1]: Entering directory `/root/git/fence-agents-sammcj/doc'
make[1]: Nothing to be done for `xml-upload'.
make[1]: Leaving directory `/root/git/fence-agents-sammcj/doc'
make[1]: Entering directory `/root/git/fence-agents-sammcj'
make[1]: Nothing to be done for `xml-upload-am'.
make[1]: Leaving directory `/root/git/fence-agents-sammcj'
root@dev-samm-01:~/git/fence-agents-sammcj  # echo $?
0
```

For something as trivial as updating documentation / fixing a broken link I think either it's overly complicated or I've made a real mess of it by missing some documentation somewhere (highly probable!).

Note that I couldn't find documentation for contributing and following the link for the [User and developer documentation](https://github.com/ClusterLabs/fence-agents/blob/master/doc/FenceAgentAPI.md) takes to you the API's documentation that doesn't mention `make xml-upload` anywhere.

**Comment by sammcj** [comment]
FYI @oalbrigt - I ended up correcting the test XML data manually - the tests should now pass for this update.

It would be good to have a contribution / development / build guide at least to cover updating existing providers descriptions / links.

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
Thanks. I'll look into adding a small section for contribution, or link to that section in the resource-agents developers guide.

**Comment by sammcj** [comment]
Thanks and please let me know if there's some doco / instructions I didn't follow that lead me astray with regards to making the new test XML.

**Comment by oalbrigt** [comment]
It seems like there's a minor issue making it not build the fencing library, so you'd have to run "make" manually first to make it work due to that issue.

**Comment by sammcj** [comment]
ah right, so while I ran `./autogen.sh` and `./configure` which made `make xml-upload` available, it's the `make` itself that builds the python libraries required for `make xml-upload`?

**Comment by oalbrigt** [comment]
"make" generates the fencing-library and agents (replacing python #! and library-path based on input from ./configure).

**Comment by sammcj** [comment]
Understood, thank you for taking the time to explain that to me.

The reason I asked is - because this was a non-functional change I didn't actually make the change in a build environment all setup for building fence-agents as it lowered the entry barrier for me to make an improvement / correction (maybe that's cheeky but I didn't budget time for making a full work build environment for a minor update).

Perhaps two things from this in my mind (and I might be wrong):

1. Perhaps some brief 'how to build / contribute' bullet points would be helpful (or perhaps some hints in the autogen.sh e.g. 'now run ./configure && make && make xml-upload' or something.
1. I'm not sure if you should really need a fully prepared build environment with its dependencies installed and built just to contribute a small / non-functional change, but perhaps to detect that it's a non-functional change might require more logic / coding than it's worth (I'm not sure what you're ratio of 3rd party contributions is).

Anyway, thanks for the tiny MR given the conversation here and keep up the great work 👍 (no further response expected).

-Sam.

**Pull request merged**
