### PR TITLE
azure_fence: fix support for sovereign clouds and MSI for new versions of azure libraries

### PR DESCRIPTION
**Pull request by MSSedusch**
fix support for Azure Sovereign clouds like China or USGov and MSI support

### CODE REVIEW

**Comment by oalbrigt** [comment]
We still need to fallback to the old code for distros that havent go the latest versions of the libs.

**Comment by MSSedusch** [comment]
@oalbrigt can you recheck? It should be backward compatible now

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Pull request merged**
