### PR TITLE
Do not record BUILD_DATE

### PR DESCRIPTION
**Pull request by bmwiedemann**
to make build reproducible.
As the preferred alternative to PR #129

### CODE REVIEW

**Comment by oalbrigt** [comment]
Looks good to me.

**Comment by marxsk** [comment]
It looks good but I'm working on a bit bigger patch that remove a bit more. @oalbrigt feel free to decide if you wish that in a single or two patches. I will remove also copyrigth notice and simplify fenceparse (or remove it at best)

**Comment by bmwiedemann** [comment]
IMHO in general it is preferable to have smaller patches - makes them easier to review and verify.
I have reviewed many hundred patches by now and the 1-4 liners are generally something you can do in under 5 minutes, but some of the bigger ones take weeks or months before you find the time.

**Comment by bmwiedemann** [comment]
closing now that #131 is merged

**Pull request closed without merging**
