### PR TITLE
fence_rhevm: added cookie file management

### PR DESCRIPTION
**Pull request by tothf**
We are using fence_rhevm many places but it was annoyingly spamming the RHV manager event logs with a new login every time the agent run status or any other actions. Reuse cookie was handy in case another action happened during the same session.
The change introduce a new option, --cookie-file. It should be full path where the cookie file should be created. By default the name is generated from the IP+username and the file created under /tmp.
This way the agent will store the cookie and use the same session until it's available. In case of manager restart new session will be opened.
In case the cookie file is stored on clustered filesystem the session will be kept in case of cluster node restarts or resource move.

### CODE REVIEW

**Comment by oalbrigt** [comment]
Looks good to me, but you also need to add the new parameter this array for it to show up in usage/metadata: https://github.com/ClusterLabs/fence-agents/blob/b885e0f65af626154096a49554e9765e18bfbbd9/agents/rhevm/fence_rhevm.py#L209

After you do that you'll have to run `make xml-upload` to update tests metadata, or our CI will fail.

**Comment by tothf** [comment]
> Looks good to me, but you also need to add the new parameter this array for it to show up in usage/metadata:
> 
> https://github.com/ClusterLabs/fence-agents/blob/b885e0f65af626154096a49554e9765e18bfbbd9/agents/rhevm/fence_rhevm.py#L209
> 
> After you do that you'll have to run `make xml-upload` to update tests metadata, or our CI will fail.

I committed the change, tried to run make xml-upload with agentpycheck.mk but it didn't work. Either "Nothing to be done" or "No rule to make target" if I specify TARGET.
Can you point me to the right direction?
Thanks

**Comment by oalbrigt** [comment]
agentpycheck.mk is used by the build system, so you dont need to use it in relation to that.

Just run the following commands in the root directory of the project:
```
./autogen.sh
./configure
make xml-upload
```

**Comment by tothf** [comment]
> agentpycheck.mk is used by the build system, so you dont need to use it in relation to that.
> 
> Just run the following commands in the root directory of the project:
> 
> ```
> ./autogen.sh
> ./configure
> make xml-upload
> ```

Thanks. Looks better now :)

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Pull request merged**
