### PR TITLE
fence_kdump: accept message from multiple addresses (useful for RRP clusters)

### PR DESCRIPTION
**Pull request by OndrejHome**
Based on proposal (and feedback from @oalbrigt) in Issue https://github.com/ClusterLabs/fence-agents/issues/370 I have prepared and tested following code that adds support for `fence_kdump` to accepts both 'single node' and 'comma-separated list of nodes' from which valid message is accepted. This should improve fence_kdump ability to receive message from more than single IP which is typically possible in RRP clusters or clusters with several heartbeat links between nodes. Check the https://github.com/ClusterLabs/fence-agents/issues/370 for more detailed explanations.

Code proposed in this PR changes the behaviour of `fence_kdump` when comma-separated list of node is provided to `--nodename`/`-n` attribute. Using only one node as done so far will NOT cause any change in behaviour. There is a minor change in debug output when using `--verbose`/`-v` option where originally `nodename` was showing argument passed. With proposed change here this shows `(null)` which matches the output from `fence_kdump_send`.
Changes in code are inspired by `fence_kdump_send` that can send messages to multiple nodes at same time and therefore has structures for storing information about multiple nodes.

Limitations/notable changes in code:
- list of nodes must use same protocol family (either all hostnames/IPs are IPv4 or all are IPv6, no mixing)
- all nodes uses same port on which message can be received (there is no code that would parse ports for different nodes)
- `read_message` function code was inlined into `do_action_off` function which is only place where code is used
- it was quite long time since I have written any C code so there most probably is something that to trained eye will look ugly/wrong - help in this area is greatly appreciated

Please let me know if code in this form can be merged or what would need changing for this to be accepted. Thank you!

# testing outputs

### IPv4
~~~
# fence_kdump -v -t 10 -n 10.0.0.78; echo $?
[debug]: options {
[debug]:     nodename = 10.0.0.78
[debug]:     ipport   = 7410
[debug]:     family   = 0
[debug]:     count    = 0
[debug]:     interval = 10
[debug]:     timeout  = 10
[debug]:     verbose  = 1
[debug]: }
[debug]: node {
[debug]:     name = 10.0.0.78
[debug]:     addr = 10.0.0.78
[debug]:     port = 7410
[debug]:     info = 0x55d2fbace420
[debug]: }
[debug]: waiting for message from '10.0.0.78'
[debug]: received valid message from '10.0.0.78'
0
~~~
~~~
# fence_kdump -t 10 -n 10.0.0.78; echo $?
[debug]: waiting for message from '10.0.0.78'
[debug]: received valid message from '10.0.0.78
0'
~~~
~~~
# fence_kdump -v -t 10 -n 10.0.0.99; echo $?
...
[debug]: waiting for message from '10.0.0.99'
[debug]: discard message from '10.0.0.78'
[debug]: discard message from '10.0.0.78'
[debug]: timeout after 10 seconds
1
~~~

### IPv6
~~~
# fence_kdump -v -t 10 -n 2002:beef::1; echo $?
[debug]: options {
[debug]:     nodename = 2002:beef::1
[debug]:     ipport   = 7410
[debug]:     family   = 0
[debug]:     count    = 0
[debug]:     interval = 10
[debug]:     timeout  = 10
[debug]:     verbose  = 1
[debug]: }
[debug]: node {
[debug]:     name = 2002:beef::1
[debug]:     addr = 2002:beef::1
[debug]:     port = 7410
[debug]:     info = 0x563151550420
[debug]: }
[debug]: waiting for message from '2002:beef::1'
[debug]: received valid message from '2002:beef::1'
0
~~~
~~~
# fence_kdump -t 10 -n 2002:beef::1; echo $?
[debug]: waiting for message from '2002:beef::1'
[debug]: received valid message from '2002:beef::1'
0
~~~
~~~
# fence_kdump -v -t 10 -n 2002:beef::3; echo $?
...
[debug]: waiting for message from '2002:beef::3'
[debug]: discard message from '2002:beef::1'
[debug]: discard message from '2002:beef::1'
[debug]: timeout after 10 seconds
1
~~~

### Unsupported scenarios
- multiple IPv4 addresses
~~~
# fence_kdump -n 10.0.0.78,192.168.2.78; echo $?
[error]: failed to get node '10.0.0.78,192.168.2.78'
1
~~~
- multiple IPv6 addresses
~~~
# fence_kdump -n 2002:beef::1,2002:deaf::1; echo $?
[error]: failed to get node '2002:beef::1,2002:deaf::1'
1
~~~
- mix of IPv4 and IPv6 addresses
~~~
# fence_kdump -n 2002:beef::1,192.168.2.78; echo $?
[error]: failed to get node '2002:beef::1,192.168.2.78'
1
~~~
=======

### IPv4
~~~
# ./fence_kdump -v -t 10 -n 10.0.0.78; echo $?
[debug]: options {        
[debug]:     nodename = (null)
[debug]:     ipport   = 7410
[debug]:     family   = 0
[debug]:     count    = 0
[debug]:     interval = 10
[debug]:     timeout  = 10
[debug]:     verbose  = 1
[debug]: }                
[debug]: node {       
[debug]:     name = 10.0.0.78
[debug]:     addr = 10.0.0.78
[debug]:     port = 7410
[debug]:     info = 0x5579c21f4420
[debug]: }            
[debug]: waiting for message from '10.0.0.78'
[debug]: received valid message from '10.0.0.78'
0
~~~
~~~
# ./fence_kdump -t 10 -n 10.0.0.78; echo $?
[debug]: waiting for message from '10.0.0.78'
[debug]: received valid message from '10.0.0.78'
0
~~~
~~~
# ./fence_kdump -v -t 10 -n 10.0.0.99; echo $?
...
[debug]: waiting for message from '10.0.0.99'
[debug]: discard message from '10.0.0.78'
[debug]: discard message from '10.0.0.78'
[debug]: timeout after 10 seconds
1
~~~

### IPv6
~~~
# ./fence_kdump -v -t 10 -n 2002:beef::1; echo $?
[debug]: options {        
[debug]:     nodename = (null)
[debug]:     ipport   = 7410
[debug]:     family   = 0
[debug]:     count    = 0
[debug]:     interval = 10
[debug]:     timeout  = 10
[debug]:     verbose  = 1
[debug]: }                
[debug]: node {       
[debug]:     name = 2002:beef::1
[debug]:     addr = 2002:beef::1
[debug]:     port = 7410
[debug]:     info = 0x5560a10ff420
[debug]: }            
[debug]: waiting for message from '2002:beef::1'
[debug]: received valid message from '2002:beef::1'
0
~~~
~~~
# ./fence_kdump -t 10 -n 2002:beef::1; echo $?
[debug]: waiting for message from '2002:beef::1'
[debug]: received valid message from '2002:beef::1'
0
~~~
~~~
# ./fence_kdump -v -t 10 -n 2002:beef::3; echo $?
...
[debug]: waiting for message from '2002:beef::3'
[debug]: discard message from '2002:beef::1'
[debug]: discard message from '2002:beef::1'
[debug]: timeout after 10 seconds
1
~~~

### Newly supported scenarios
- multiple IPv4 addresses
~~~
# ./fence_kdump -n 10.0.0.78,192.168.2.78; echo $?
[debug]: waiting for message from '10.0.0.78'
[debug]: waiting for message from '192.168.2.78'
[debug]: received valid message from '10.0.0.78'
0
~~~
~~~
# ./fence_kdump -n 10.0.0.78,192.168.2.78; echo $?
[debug]: waiting for message from '10.0.0.78'
[debug]: waiting for message from '192.168.2.78'
[debug]: received valid message from '192.168.2.78'
0
~~~
- multiple IPv6 addresses
~~~
# ./fence_kdump -n 2002:beef::1,2002:deaf::1; echo $?
[debug]: waiting for message from '2002:beef::1'
[debug]: waiting for message from '2002:deaf::1'
[debug]: received valid message from '2002:beef::1'
0
~~~
~~~
# ./fence_kdump -n 2002:beef::1,2002:deaf::1; echo $?
[debug]: waiting for message from '2002:beef::1'
[debug]: waiting for message from '2002:deaf::1'
[debug]: received valid message from '2002:deaf::1'
0
~~~
### Unsupported scenarios
- mix of IPv4 and IPv6 addresses
~~~
# ./fence_kdump -n 2002:beef::1,192.168.2.78; echo $?
[debug]: waiting for message from '2002:beef::1'
[debug]: waiting for message from '192.168.2.78'
[error]: mixing IPv4 and IPv6 nodes is not supported
1
~~~

### CODE REVIEW

**Comment by OndrejHome** [comment]
Hi, just wanted to remind about existenxe of this PR. Would some one be able to have a look? Thank you!

**Comment by oalbrigt** [comment]
I'll have a look. I was hoping we could do this with a lot less changes.

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Comment by OndrejHome** [comment]
Thank you!

In case that some was looking for example on how this can be used with `pcs` I and how it compares to previous configurations I have put it together into blog post here - http://www.famera.cz/blog/computers/fence_kdump_rrp.html#after-the-rrp-patch-configuration-example

**Comment by oalbrigt** [comment]
I think it should also work with `pcmk_host_map=host1:ip1,ip2;host2...`.

**Comment by OndrejHome** [comment]
> I think it should also work with `pcmk_host_map=host1:ip1,ip2;host2....`

Surprisingly it is not working :/ I can see that pacemaker tries to pass `port=ip1,ip2`, but fence_kdump actually doesn't have a `port` option. However by some "magic" it ends up waiting for message from just the nodename

~~~
Aug 01 10:59:38 pacemaker-fenced    [7395] (can_fence_host_with_device)    notice: kdump is eligible to fence (reboot) fastvm-centos-8-3-79 (aka. '192.168.2.79,10.0.0.79'): static-list
Aug 01 10:59:38 pacemaker-fenced    [7395] (make_args)     debug: Performing 'off' action targeting 'fastvm-centos-8-3-79' as 'port=192.168.2.79,10.0.0.79'
Aug 01 10:59:38 fence_kdump[7463]: waiting for message from '192.168.2.79'
~~~

And by "magic" I mean the `port` gets ignored completely if I intentionally put wrong IPs in pcmk_host_map.
~~~
Aug 01 11:22:46 pacemaker-fenced    [15198] (make_args)    debug: Passing port='10.1.1.1,10.0.0.79' with fence action off targeting fastvm-centos-8-3-79
Aug 01 11:22:46 fence_kdump[21264]: waiting for message from '192.168.2.79'
~~~

I will have a look at this, but I suspect that `fence_kdump` would need to "learn" the 'port' option.

Btw, any hints on how to get content that pacemaker pipes to fence agent when fencing is invoked?

I assume that pacemaker does something like `echo "xxx" | fence_kdump`, but I'm not sure how to get to the content of xxx. I have tried `PCMK_debug=yes` and also tried `PCMK_trace_functions=pipe_in_action_stdin_parameters,fork_cb` without success - no extra data were seen in logs. (pacemaker-2.0.5 on CentOS 8.4).

**Comment by oalbrigt** [comment]
We might have to add "plug" parameter for that.

**Comment by oalbrigt** [comment]
Known issue with pcmk_host_map: https://access.redhat.com/solutions/3553151

**Pull request merged**
