### PR TITLE
build: some cleanups to release.mk

### PR DESCRIPTION
**Pull request by jnpkrn**
Based upon https://github.com/ClusterLabs/libqb/pull/260

### CODE REVIEW

**Comment by oalbrigt** [comment]
Thanks.

Can you remove the \@echo-part regarding scp? We'll just do that if we decide to do it for the other projects.

**Comment by jnpkrn** [comment]
On 22/06/17 02:51 -0700, Oyvind Albrigtsen wrote:
> Can you remove the \@echo-part regarding scp? We'll just do that if
> we decide to do it for the other projects.

Do you mean whole block starting with `Since` and ending with
`NOTE`?

There's actually a precedent of this "decision-pending" state in the
other project if you take a look at the referenced
https://github.com/ClusterLabs/libqb/pull/260

Or can I just comment that block out so it doesn't clutter the screen
for now?

Is currently `make -f make/publish.mk publish` being used at all?

-- 
Jan (Poki)

**Comment by oalbrigt** [comment]
Yeah, you can just remove that block. We'll do the decision based on what is decided in e.g. libqb.

We still use the publish function.

**Comment by jnpkrn** [comment]
OK, adjusted.

**Comment by oalbrigt** [comment]
Thanks.

**Pull request merged**
