### PR TITLE
fence_lindypdu: new fence agent

### PR DESCRIPTION
**Pull request by cesello**
New fence agent for Lindy PDU model 32657 (8-16 plugs)

### CODE REVIEW

**Comment by oalbrigt** [comment]
Can you update the commit message to "fence_lindypdu: new fence agent"?

**Comment by oalbrigt** [comment]
And you need to run `make xml-upload` and attach the metadata file it creates to avoid failing CI when I tell it to test the PR.

**Comment by cesello** [comment]
Hi Oyvind
maybe a stupid question but I'm new here:
after make xml-upload
I have to commit the created xml file or attach it  somewhere ?

Thnks

**Comment by oalbrigt** [comment]
Add it to the commit.

**Pull request closed without merging**
