### PR TITLE
fence_redfish: add headers to HTTP methods

### PR DESCRIPTION
**Pull request by jose-delarosa**
* Needed for full compliance with Redfish spec.
* May cause errors in some devices if not sent.

### CODE REVIEW

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Comment by oalbrigt** [comment]
Have you seen any issues with fencing not working due to this, or do you just get errors in the device log?

**Comment by jose-delarosa** [comment]
@oalbrigt I have seen errors in some devices where the fencing operation fails (HTTP Error 406). Not every device enforces the presence of these headers, but some do. Adding these headers makes it compliant with the Redfish spec (see [here](https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.6.1.pdf), page 26).

**Comment by oalbrigt** [comment]
Thanks for the information. That helps prioritize adding it in distros higher than if it was just causing error messages.

**Pull request merged**
