### PR TITLE
readd fence-virt

### PR DESCRIPTION
**Pull request by fabbione**

### CODE REVIEW

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
@oalbrigt PR is ready. 2 important details/things:

fence_virt will need some major testing due to f82719dcf1be076e1171ca7741b96b7c419d8efa. This is one of those code changes that are difficult to get right without knowing the whole code.

I did add and then later removed -Werror because of fence_zvm. There is a simple warning there, than when fixed makes gcc goes ballistic on s390. It probably needs a semi-full rewrite.

Given that, it´s ready to go in.

Once in, we will need to do some more changes to CI migrate clang and covscan jobs from fence-virt to fas, but that´s "easy".

**Comment by fabbione** [comment]
@oalbrigt I found the build issue with fence_zvm and re-added -Werror now.

**Review by oalbrigt — APPROVED** [review]
LGTM

**Pull request merged**
