### PR TITLE
Fencing Agent for Openstack

### PR DESCRIPTION
**Pull request by cosmo83**
This is a Simple Fencing Agent for Openstack VMs. Tested with Openstack Newton, and should work with Keystone V3.

This agent calls the python-novaclient and it is mandatory to be installed

### CODE REVIEW

**Comment by oalbrigt** [comment]
Run "make xml-upload" to update the metadata.

**Comment by oalbrigt** [comment]
add to whitelist

**Comment by beekhof** [comment]
Maybe "fence_openstack" instead?

**Comment by beekhof** [comment]
It might be a good idea to have a common source for the authentication logic (borrowed from fence_compute)

**Comment by oalbrigt** [comment]
@marxsk what do you think regarding name for this?

**Comment by marxsk** [comment]
@oalbrigt I'm fine with fence_openstack

**Comment by oalbrigt** [comment]
@cosmo83 can you rename it to fence_openstack? I'll take care of splitting out the auth logic when I've merged it.

**Comment by oalbrigt** [comment]
Thanks.

**Comment by oalbrigt** [comment]
@cosmo83 Can you have a look at https://github.com/ClusterLabs/fence-agents/pull/242
and see what works with your version of novaclient?

**Pull request merged**
