### PR TITLE
fence_lindypdu: new fence agent

### PR DESCRIPTION
**Pull request by cesello**
New fence agent for Lindy PDU model 32657 (8-16 plugs)

### CODE REVIEW

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
retest this please

**Comment by cesello** [comment]
Sorry I can't see the problem.
Into the jenkins compilation messages
I see only redhat and fedora failures with for this error apparently

 http://download.eng.rdu.redhat.com/released/RHEL-7/7.9/Server/s390x/os/repodata/repomd.xml:
[Errno 14] curl#6 - "Could not resolve host:
download.eng.rdu.redhat.com; Unknown error"

nothing related to my python agent script

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Pull request merged**
