### PR TITLE
Update drac5 to support drac8 ssh fence agent

### PR DESCRIPTION
**Pull request by Klaas-**
This adds a dell drac ssh fence agent, I tested it with drac8. I looked at the tests in tests/data/metadata/fence_ilo_ssh.xml - they should all apply to drac aswell but essentially testing the common parts once should be enough I'd guess :)

### CODE REVIEW

**Comment by Klaas-** [comment]
seems like the tests are needed for automated testing to pass, I'll fix them tonight

**Comment by Klaas-** [comment]
hmm I didn't notice the fence_drac5 is also ssh :) I'll integrate drac8 into that

**Comment by oalbrigt** [comment]
Great. FYI you can run "make xml-upload" to update the test-metadata.

**Comment by Klaas-** [comment]
its just a one line fix in the right file :D

**Comment by Klaas-** [comment]
should I note somewhere that I had to significantly increase the shell/power timeout?

**Comment by Klaas-** [comment]
@oalbrigt ping :)

**Comment by marxsk** [comment]
@Klaas- yes, if is required for standard operation that you (or @oalbrigt ) can think about adding a new symlink with different default values, like we already do for fence_ipmi

**Pull request closed without merging**
