### PR TITLE
fence_sbd: Add a fencing agent for sbd

### PR DESCRIPTION
**Pull request by disco-stu**
Add a STONITH agent for SDB (STORAGE BASED DEATH).

Signed-off-by: Adrian Vondendriesch <adrian.vondendriesch@credativ.de>

### CODE REVIEW

**Comment by marxsk** [comment]
I have created a pull request on your repo with my comments.

**Comment by disco-stu** [comment]
I'm fine with "--devices". Keeping this parameter equal over the different fencing agents seems reasonable to me.

**Comment by marxsk** [comment]
Sorry, for being late. I will import patches next week.

**Comment by disco-stu** [comment]
No problem. Let me know if my patch needs any further improvements.

**Comment by marxsk** [comment]
ok, merged as a single commit.

**Pull request closed without merging**
