### PR TITLE
fencing: Specify command to be logged by run_command

### PR DESCRIPTION
**Pull request by n3world**
Currently run_command special cases the logging of commands with ipmitool and removes everything
between the flat -P and -p. Instead of special casing commands with ipmitool allow the caller to
provide the command to log so that the command can do any necessary scrubbing of the message to be
logged.

### CODE REVIEW

**Comment by n3world** [comment]
It looks like the build failed because it couldn't find python library path, but I am not sure how my change would have caused that.

**Comment by krig** [comment]
It is an unrelated failure, the fix in in pull request #96.

**Comment by oalbrigt** [comment]
This seems to work as expected, and is to avoid logging the password. The reason for the "special casing" is that ipmitool uses -P for password and -p for port.

**Comment by n3world** [comment]
The current code works ok for ipmitool but not for anything else. It also just replaces everything between -P and -p which could be other arguments and not just the password. If you look at fence_ipmilan you can see that the cipher argument can occur between -P and -p so that would be lost in the logging. This change was just to provide a more generic interface to scrubbing the logging of a command so that any agent can specify the log message for a command in case it also has a password or other sensitive information on the commandline.

**Pull request merged**
