### PR TITLE
Do not provide tenant name in place for tenant ID.

### PR DESCRIPTION
**Pull request by jsuchome**
novaclient expects project ID as a positional argument, and
the fence_compute was providing tenant name instead.
Correct way of providing tenant name is with project_name key.

### CODE REVIEW

**Comment by aspiers** [comment]
@jsuchome Thanks! But how did this ever work before? Has something changed in novaclient?

**Comment by jsuchome** [comment]
I have no idea, it seems the change in nova-client is pretty old, as Colleen found out: https://github.com/openstack/python-novaclient/commit/9bbe5a87b7df62a7962debba5db7c96555da6761

**Comment by beekhof** [comment]
I'll be merging https://github.com/beekhof/fence-agents/commit/88c1542454b1527fb24a7b3722fd1bf892b5ce07 soon which is more backwardly compatible

**Comment by jsuchome** [comment]
Makes sense.

**Comment by aspiers** [comment]
@beekhof to the rescue, hooray! :-)

**Pull request closed without merging**
